name: Build

on:
  push:
    paths: ["repo/**", "!repo/x86_64/**", ".github/workflows/*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:3.19
    steps:
      - name: Setup deps
        run: |
          apk add aports-build
          adduser --ingroup abuild --disabled-password foo
          mkdir /home/foo/.abuild

      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: key test
        run: |
          su foo -c 'abuild-keygen -aq'
          mv /home/foo/.abuild .

     # - name: Setup keys
      #  run: |
       #   cp ./bttm-6650b009.rsa.pub /home/foo/.abuild/
        #  cp ./bttm-6650b009.rsa.pub /etc/apk/keys/
         # echo "${{ secrets.APORTS_PRIVATE_KEY }}" > /home/foo/.abuild/bttm-6650b009.rsa
          #echo "PACKAGER_PRIVKEY=/home/foo/.abuild/bttm-6650b009.rsa" > /home/foo/.abuild/abuild.conf

      - name: Change ownership to build
        run: chown -R foo $(pwd)

      - name: test
        run: chown -R foo /home/foo

      - name: Build repo
        run: su foo -c 'buildrepo --destdir $(pwd) --aports $(pwd) --purge repo'

      - name: Revert ownership to git
        run: chown -R root $(pwd)

      - name: Commit new packages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "upgrade packages"
          git push
